project:
  type: website

website:
  title: "total-empiricism"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/total-empiricism/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

